apiVersion: v1
kind: ConfigMap
metadata:
  name: eshop-web-config
  namespace: kiii
data:
  DB_HOST: sql_server
  DB_NAME: GymAPP
  DB_SA_PASSWORD: marko@123
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-server-secret
  namespace: kiii
type: Opaque
data:
  SA_PASSWORD: bWFya28rMTIz
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eshop-web-mssql-pvc
  namespace: kiii
  labels:
    app: eshop-web
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eshop-web-mssql
  namespace: kiii
spec:
  serviceName: eshop-web-mssql-service
  selector:
    matchLabels:
      app: eshop-web
  replicas: 1
  template:
    metadata:
      labels:
        app: eshop-web
        namespace: kiii
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server
          envFrom:
            - configMapRef:
                name: eshop-web-config
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-server-secret
                  key: marko@123
          ports:
            - containerPort: 1433
              name: sql-server-port
          volumeMounts:
            - name: eshop-web-mssql-pvc
              mountPath: /var/opt/mssql/data
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: eshop-web-mssql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-web-mssql-service
  namespace: kiii
spec:
  selector:
    app: eshop-web
  ports:
    - protocol: TCP
      port: 1433