apiVersion: v1
kind: ConfigMap
metadata:
  name: eshop-web-config
  namespace: kiii
data:
  DB_HOST: sql_server
  DB_NAME: GymAPP
  DB_SA_PASSWORD: marko@123
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-server-secret
  namespace: kiii
type: Opaque
data:
  SA_PASSWORD: bWFya28rMTIz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-web-deployment
  namespace: kiii
spec:
  replicas: 5
  selector:
    matchLabels:
      app: eshop-web
  template:
    metadata:
      labels:
        app: eshop-web
    spec:
      containers:
        - name: eshop-web
          image: eshop-web
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: eshop-web-config
          env:
            - name: DB_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-server-secret
                  key: password